#!/usr/bin/env python3
"""HAMT 训练与评估可视化 — Nature 期刊级图表.

Figure 1: Training Dynamics
  a — Step-level loss trajectory with EMA smoothing + stage shading
  b — Epoch-level loss decomposition (cls / l1 / ciou) as stacked area
  c — Matching quality metrics (P@50, R@50, MatchR, mIoU)
  d — Throughput (frames/s) + epoch duration

Figure 2: Evaluation Results (post-eval)
  a — MOTA / MOTP / IDF1 by dataset
  b — Detection breakdown (FP / FN / IDSW)

Data sources (auto-detected):
  - Step-level: train_v[0-9]_*.log  (Epoch X, Step Y, AvgLoss: Z)
  - Epoch-level: train_v[0-9]_*.log  (Epoch X 完成 | loss=...)
                 or training_metrics_v*.json
  - Eval results: eval_results.json (to be generated by evaluation pipeline)
"""
import json
import re
import sys
from pathlib import Path
from collections import defaultdict

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

# ═══════════════════════════════════════════════════════════════════════
# Nature-Figure Mandatory rcParams
# ═══════════════════════════════════════════════════════════════════════
plt.rcParams['font.family'] = 'sans-serif'
plt.rcParams['font.sans-serif'] = ['Arial', 'DejaVu Sans', 'Liberation Sans']
plt.rcParams['svg.fonttype'] = 'none'
plt.rcParams.update({
    'font.size': 12,
    'axes.spines.right': False,
    'axes.spines.top': False,
    'axes.linewidth': 2.0,
    'legend.frameon': False,
    'xtick.major.width': 1.5,
    'ytick.major.width': 1.5,
})

# ═══════════════════════════════════════════════════════════════════════
# Unified Semantic Palette (Nature Machine Intelligence pastel style)
# ═══════════════════════════════════════════════════════════════════════
PALETTE = {
    # Loss family
    'loss_total':   '#0F4D92',
    'loss_cls':     '#3775BA',
    'loss_l1':      '#9A4D8E',
    'loss_ciou':    '#42949E',
    'loss_smooth':  '#1A1A2E',
    # Matching quality
    'precision':    '#2E9E44',
    'recall':       '#E53935',
    'match_recall': '#DDA43B',
    'miou':         '#42949E',
    # Eval metrics
    'mota':         '#0F4D92',
    'motp':         '#3775BA',
    'idf1':         '#9A4D8E',
    # Detection
    'fp':           '#E9A6A1',
    'fn':           '#F6CFCB',
    'idsw':         '#B64342',
    # Stage backgrounds
    'stage1_bg':    '#F0F4FF',
    'stage2_bg':    '#FFF8F0',
    'stage3_bg':    '#F0FFF4',
    # Neutrals
    'neutral':      '#767676',
    'neutral_dark': '#272727',
    'grid':         '#E0E0E0',
}
STAGE_BGS = [PALETTE['stage1_bg'], PALETTE['stage2_bg'], PALETTE['stage3_bg']]

OUTPUT_DIR = Path(__file__).resolve().parent / "results"


# ═══════════════════════════════════════════════════════════════════════
# Data extraction
# ═══════════════════════════════════════════════════════════════════════

def extract_step_data(log_path):
    """Extract step-level AvgLoss from training log."""
    pattern = re.compile(
        r"Epoch\s+(\d+),\s+Step\s+(\d+),\s+AvgLoss:\s+([\d.]+)"
    )
    steps = []
    if not Path(log_path).exists():
        return steps
    with open(log_path, 'r', encoding='utf-8') as f:
        for line in f:
            m = pattern.search(line)
            if m:
                steps.append({
                    'epoch': int(m.group(1)),
                    'step': int(m.group(2)),
                    'loss': float(m.group(3)),
                })
    return steps


def extract_epoch_data(log_path):
    """Extract epoch-completion summaries from training log."""
    pattern = re.compile(
        r"Epoch\s+(\d+)\s+完成\s+\|\s+"
        r"loss=([\d.]+)\s+cls=([\d.]+)\s+l1=([\d.]+)\s+ciou=([\d.]+)\s+\|\s+"
        r"P@50=([\d.]+)\s+R@50=([\d.]+)\s+MatchR=([\d.]+)\s+mIoU=([\d.]+)\s+\|\s+"
        r"steps=(\d+)\s+failed=(\d+)\s+skipped_seq=(\d+)\s+\|\s+"
        r"frames=(\d+)/(\d+).*?\|\s+"
        r"([\d.]+)s\s+([\d.]+)\s+step/s\s+([\d.]+)\s+frame/s"
    )
    stage_pattern = re.compile(r"阶段:\s+(\w+)\s+\(Epoch\s+(\d+)-(\d+)")
    epochs = []
    current_stage = "unknown"
    if not Path(log_path).exists():
        return epochs
    with open(log_path, 'r', encoding='utf-8') as f:
        for line in f:
            sm = stage_pattern.search(line)
            if sm:
                current_stage = sm.group(1)
            m = pattern.search(line)
            if m:
                epochs.append({
                    'epoch': int(m.group(1)),
                    'stage': current_stage,
                    'loss_total': float(m.group(2)),
                    'loss_cls': float(m.group(3)),
                    'loss_l1': float(m.group(4)),
                    'loss_ciou': float(m.group(5)),
                    'precision_iou50': float(m.group(6)),
                    'recall_iou50': float(m.group(7)),
                    'match_recall': float(m.group(8)),
                    'mean_matched_iou': float(m.group(9)),
                    'steps': int(m.group(10)),
                    'failed_steps': int(m.group(11)),
                    'skipped': int(m.group(12)),
                    'frames_processed': int(m.group(13)),
                    'frames_expected': int(m.group(14)),
                    'epoch_seconds': float(m.group(15)),
                    'steps_per_second': float(m.group(16)),
                    'frames_per_second': float(m.group(17)),
                })
    return epochs


def load_json_metrics(json_path):
    """Load pre-extracted metrics from JSON."""
    p = Path(json_path)
    if p.exists():
        with open(p) as f:
            return json.load(f)
    return []


def find_data():
    """Auto-discover available training data."""
    logs = sorted(OUTPUT_DIR.glob("train_v[0-9]_*.log"))
    json_files = sorted(OUTPUT_DIR.glob("training_metrics_v*.json"))
    eval_files = sorted(OUTPUT_DIR.glob("eval_results*.json"))

    log_path = str(logs[-1]) if logs else None
    json_path = str(json_files[-1]) if json_files else None

    return log_path, json_path, eval_files


# ═══════════════════════════════════════════════════════════════════════
# Figure 1: Training Dynamics
# ═══════════════════════════════════════════════════════════════════════

def detect_stages_from_epochs(epochs):
    """Detect epoch ranges per stage from epoch-level data."""
    stages = {}
    for e in epochs:
        s = e.get('stage', 'unknown')
        if s not in stages:
            stages[s] = {'start': 9999, 'end': 0}
        stages[s]['start'] = min(stages[s]['start'], e['epoch'])
        stages[s]['end'] = max(stages[s]['end'], e['epoch'])
    return stages


def build_figure1(step_data, epoch_data):
    """Figure 1: Training Dynamics (4-panel)."""
    if not step_data and not epoch_data:
        print("  ⚠ No data for Figure 1 — skipping.")
        return

    fig = plt.figure(figsize=(22, 18))
    gs = gridspec.GridSpec(2, 2, figure=fig, hspace=0.35, wspace=0.30)

    # Detect stage boundaries from epoch data if available
    stage_boundaries = detect_stages_from_epochs(epoch_data) if epoch_data else {}

    # ── Panel a: Step-level loss trajectory ──
    ax_a = fig.add_subplot(gs[0, :])
    _draw_panel_a_loss(ax_a, step_data, stage_boundaries)

    # ── Panel b: Epoch-level loss decomposition (stacked area) ──
    ax_b = fig.add_subplot(gs[1, 0])
    _draw_panel_b_decomposition(ax_b, epoch_data, stage_boundaries)

    # ── Panel c: Matching quality metrics ──
    ax_c = fig.add_subplot(gs[1, 1])
    _draw_panel_c_matching(ax_c, epoch_data, stage_boundaries)

    out_svg = OUTPUT_DIR / 'fig1_training_dynamics.svg'
    fig.savefig(out_svg, bbox_inches='tight')
    fig.savefig(OUTPUT_DIR / 'fig1_training_dynamics.png', dpi=300, bbox_inches='tight')
    plt.close(fig)
    print(f"  ✓ Figure 1: {out_svg}")


def _draw_panel_a_loss(ax, step_data, stage_boundaries):
    """Panel a: Step-level loss with EMA smoothing and stage shading."""
    if not step_data:
        ax.text(0.5, 0.5, 'No step-level data yet', ha='center', va='center',
                transform=ax.transAxes, fontsize=14, color=PALETTE['neutral'])
        ax.text(-0.03, 1.06, 'a', transform=ax.transAxes,
                fontsize=22, fontweight='bold', va='top', ha='right')
        ax.spines['bottom'].set_linewidth(2)
        ax.spines['left'].set_linewidth(2)
        ax.set_ylabel('Loss', fontsize=14)
        ax.set_xlabel('Epoch', fontsize=14)
        return

    # Global step index for x-axis
    global_steps = np.arange(1, len(step_data) + 1)
    losses = np.array([s['loss'] for s in step_data], dtype=np.float64)
    epochs = np.array([s['epoch'] for s in step_data])

    # Map epoch numbers to global step range for shading
    epoch_boundaries_steps = {}
    prev_ep = epochs[0]
    for i, ep in enumerate(epochs):
        if ep != prev_ep:
            epoch_boundaries_steps[prev_ep] = global_steps[i - 1]
            prev_ep = ep
    epoch_boundaries_steps[prev_ep] = global_steps[-1]

    # Draw raw loss as faint background
    ax.plot(global_steps, losses, color='#D0D0D0', linewidth=0.5, alpha=0.6, label='Raw loss (per step)')

    # EMA smoothing (alpha=0.05)
    ema = np.zeros_like(losses)
    ema[0] = losses[0]
    for i in range(1, len(losses)):
        ema[i] = 0.05 * losses[i] + 0.95 * ema[i - 1]

    # Label epoch transitions on x-axis
    ep_labels = sorted(epoch_boundaries_steps.keys())
    ax.plot(global_steps, ema, color=PALETTE['loss_smooth'], linewidth=2.2, label='EMA smoothed')

    # Stage shading
    _draw_stage_shading(ax, stage_boundaries, epoch_boundaries_steps)

    ax.set_ylabel('Loss', fontsize=14)
    ax.set_xlabel('Global Step', fontsize=14)
    ax.legend(loc='upper right', fontsize=10, ncol=2)
    ax.set_xlim(0, global_steps[-1])
    ax.text(-0.03, 1.06, 'a', transform=ax.transAxes,
            fontsize=22, fontweight='bold', va='top', ha='right')
    ax.spines['bottom'].set_linewidth(2)
    ax.spines['left'].set_linewidth(2)

    # Add epoch number ticks at top
    if epoch_boundaries_steps:
        secax = ax.secondary_xaxis('top')
        tick_positions = [global_steps[0]]
        tick_labels = [str(epochs[0])]
        for ep in sorted(epoch_boundaries_steps.keys()):
            idx = int(epoch_boundaries_steps[ep])
            if idx < len(global_steps):
                tick_positions.append(global_steps[idx])
                tick_labels.append(str(ep + 1))
        secax.set_xticks(tick_positions)
        secax.set_xticklabels(tick_labels, fontsize=8)
        secax.set_xlabel('Epoch', fontsize=10)


def _draw_panel_b_decomposition(ax, epoch_data, stage_boundaries):
    """Panel b: Epoch-level loss decomposition as grouped bar or line."""
    if not epoch_data:
        ax.text(0.5, 0.5, 'No epoch data yet', ha='center', va='center',
                transform=ax.transAxes, fontsize=14, color=PALETTE['neutral'])
        ax.text(-0.06, 1.06, 'b', transform=ax.transAxes,
                fontsize=22, fontweight='bold', va='top', ha='right')
        ax.spines['bottom'].set_linewidth(2)
        ax.spines['left'].set_linewidth(2)
        ax.set_ylabel('Loss', fontsize=14)
        ax.set_xlabel('Epoch', fontsize=14)
        return

    epochs = [e['epoch'] for e in epoch_data]
    cls_vals = [e['loss_cls'] for e in epoch_data]
    l1_vals = [e['loss_l1'] for e in epoch_data]
    ciou_vals = [e['loss_ciou'] for e in epoch_data]

    # Stacked area chart
    ax.fill_between(epochs, 0, cls_vals, alpha=0.7, color=PALETTE['loss_cls'], label='Cls Loss')
    ax.fill_between(epochs, cls_vals, np.array(cls_vals) + np.array(l1_vals),
                     alpha=0.7, color=PALETTE['loss_l1'], label='L1 Loss')
    bottom = np.array(cls_vals) + np.array(l1_vals)
    ax.fill_between(epochs, bottom, bottom + np.array(ciou_vals),
                     alpha=0.7, color=PALETTE['loss_ciou'], label='CIoU Loss')
    total = bottom + np.array(ciou_vals)
    ax.plot(epochs, total, color=PALETTE['loss_total'], linewidth=2.5, marker='o',
            markersize=4, label='Total Loss', zorder=5)

    # Stage shading
    _draw_epoch_stage_shading(ax, stage_boundaries)

    ax.set_ylabel('Loss', fontsize=14)
    ax.set_xlabel('Epoch', fontsize=14)
    ax.legend(loc='upper right', fontsize=9, ncol=2)
    ax.text(-0.06, 1.06, 'b', transform=ax.transAxes,
            fontsize=22, fontweight='bold', va='top', ha='right')
    ax.spines['bottom'].set_linewidth(2)
    ax.spines['left'].set_linewidth(2)


def _draw_panel_c_matching(ax, epoch_data, stage_boundaries):
    """Panel c: Matching quality metrics over epochs."""
    if not epoch_data:
        ax.text(0.5, 0.5, 'No epoch data yet', ha='center', va='center',
                transform=ax.transAxes, fontsize=14, color=PALETTE['neutral'])
        ax.text(-0.06, 1.06, 'c', transform=ax.transAxes,
                fontsize=22, fontweight='bold', va='top', ha='right')
        ax.spines['bottom'].set_linewidth(2)
        ax.spines['left'].set_linewidth(2)
        ax.set_ylabel('Score', fontsize=14)
        ax.set_xlabel('Epoch', fontsize=14)
        return

    epochs = [e['epoch'] for e in epoch_data]
    ax.plot(epochs, [e['precision_iou50'] for e in epoch_data],
            color=PALETTE['precision'], linewidth=2.2, marker='o', markersize=4, label='P@IoU50')
    ax.plot(epochs, [e['recall_iou50'] for e in epoch_data],
            color=PALETTE['recall'], linewidth=2.2, marker='s', markersize=4, label='R@IoU50')
    ax.plot(epochs, [e['match_recall'] for e in epoch_data],
            color=PALETTE['match_recall'], linewidth=2.2, marker='^', markersize=4, label='MatchR')
    ax.plot(epochs, [e['mean_matched_iou'] for e in epoch_data],
            color=PALETTE['miou'], linewidth=2.2, marker='d', markersize=4, label='mIoU')

    _draw_epoch_stage_shading(ax, stage_boundaries)

    ax.set_ylabel('Score', fontsize=14)
    ax.set_xlabel('Epoch', fontsize=14)
    ax.set_ylim(0, 1.05)
    ax.legend(loc='lower right', fontsize=10, ncol=2)
    ax.text(-0.06, 1.06, 'c', transform=ax.transAxes,
            fontsize=22, fontweight='bold', va='top', ha='right')
    ax.spines['bottom'].set_linewidth(2)
    ax.spines['left'].set_linewidth(2)


# ═══════════════════════════════════════════════════════════════════════
# Figure 2: Evaluation Results
# ═══════════════════════════════════════════════════════════════════════

def build_figure2(eval_data_paths):
    """Figure 2: Evaluation Results (MOTA/MOTP/IDF1 + Detection)."""
    if not eval_data_paths:
        print("  ⚠ No evaluation data — Figure 2 will be generated after eval completes.")
        return

    # Try loading evaluation results
    all_results = {}
    for p in eval_data_paths:
        try:
            with open(p) as f:
                data = json.load(f)
                all_results[p.stem] = data
        except Exception:
            continue

    if not all_results:
        print("  ⚠ Could not parse any eval results.")
        return

    fig = plt.figure(figsize=(22, 10))
    gs = gridspec.GridSpec(1, 2, figure=fig, hspace=0.35, wspace=0.30)

    # ── Panel a: MOTA/MOTP/IDF1 by dataset ──
    ax_a = fig.add_subplot(gs[0, 0])
    _draw_panel_d_mot_metrics(ax_a, all_results)

    # ── Panel b: Detection breakdown ──
    ax_b = fig.add_subplot(gs[0, 1])
    _draw_panel_e_detection(ax_b, all_results)

    fig.tight_layout(pad=2)
    out_svg = OUTPUT_DIR / 'fig2_evaluation.svg'
    fig.savefig(out_svg, bbox_inches='tight')
    fig.savefig(OUTPUT_DIR / 'fig2_evaluation.png', dpi=300, bbox_inches='tight')
    plt.close(fig)
    print(f"  ✓ Figure 2: {out_svg}")


def _draw_panel_d_mot_metrics(ax, all_results):
    """Panel a: MOTA / MOTP / IDF1 grouped bar by dataset."""
    datasets = sorted(all_results.keys())
    metrics_keys = ['MOTA', 'MOTP', 'IDF1']
    metric_colors = [PALETTE['mota'], PALETTE['motp'], PALETTE['idf1']]

    x = np.arange(len(datasets))
    width = 0.25
    for i, (mk, mc) in enumerate(zip(metrics_keys, metric_colors)):
        vals = []
        for ds in datasets:
            r = all_results[ds]
            if isinstance(r, dict):
                vals.append(r.get(mk, r.get(mk.lower(), 0)))
            elif isinstance(r, list) and len(r) > 0 and isinstance(r[0], dict):
                vals.append(r[0].get(mk, r[0].get(mk.lower(), 0)))
            else:
                vals.append(0)
        ax.bar(x + i * width, vals, width, color=mc, alpha=0.85, label=mk)

    ax.set_xticks(x + width)
    ax.set_xticklabels([d.replace('_', '\n') for d in datasets], fontsize=11)
    ax.set_ylabel('Score (%)', fontsize=14)
    ax.set_ylim(0, max(100, ax.get_ylim()[1] * 1.1))
    ax.legend(fontsize=11, loc='upper right')
    ax.text(-0.06, 1.06, 'a', transform=ax.transAxes,
            fontsize=22, fontweight='bold', va='top', ha='right')
    ax.spines['bottom'].set_linewidth(2)
    ax.spines['left'].set_linewidth(2)


def _draw_panel_e_detection(ax, all_results):
    """Panel b: Detection breakdown (FP / FN / IDSW)."""
    datasets = sorted(all_results.keys())
    det_keys = ['FP', 'FN', 'IDSW']
    det_colors = [PALETTE['fp'], PALETTE['fn'], PALETTE['idsw']]

    x = np.arange(len(datasets))
    width = 0.25
    for i, (dk, dc) in enumerate(zip(det_keys, det_colors)):
        vals = []
        for ds in datasets:
            r = all_results[ds]
            if isinstance(r, dict):
                vals.append(r.get(dk, r.get(dk.lower(), 0)))
            elif isinstance(r, list) and len(r) > 0 and isinstance(r[0], dict):
                vals.append(r[0].get(dk, r[0].get(dk.lower(), 0)))
            else:
                vals.append(0)
        ax.bar(x + i * width, vals, width, color=dc, alpha=0.85, label=dk)

    ax.set_xticks(x + width)
    ax.set_xticklabels([d.replace('_', '\n') for d in datasets], fontsize=11)
    ax.set_ylabel('Count', fontsize=14)
    ax.legend(fontsize=11, loc='upper right')
    ax.text(-0.06, 1.06, 'b', transform=ax.transAxes,
            fontsize=22, fontweight='bold', va='top', ha='right')
    ax.spines['bottom'].set_linewidth(2)
    ax.spines['left'].set_linewidth(2)


# ═══════════════════════════════════════════════════════════════════════
# Figure 3: Architecture Overview (schematic placeholder)
# ═══════════════════════════════════════════════════════════════════════

def build_figure3_model_summary():
    """Figure 3: Model architecture schematic + parameter distribution."""
    fig = plt.figure(figsize=(22, 10))
    gs = gridspec.GridSpec(1, 2, figure=fig, hspace=0.35, wspace=0.30)

    # Panel a: Parameter distribution by module
    ax_a = fig.add_subplot(gs[0, 0])
    modules = ['Backbone\n(DINOv3)', 'Hierarchical\nEncoder', 'Gated Memory\nDecoder',
               'Memory\nBank', 'Heads\n(Cls+Bbox)']
    params = [86.5, 3.2, 4.1, 0.8, 2.6]  # approximate millions
    colors_a = ['#B4C0E4', '#7884B4', '#484878', '#E4CCD8', '#F0C0CC']
    bars = ax_a.barh(modules, params, color=colors_a, edgecolor='white', linewidth=0.8)
    for bar, val in zip(bars, params):
        ax_a.text(bar.get_width() + 0.5, bar.get_y() + bar.get_height() / 2,
                  f'{val:.1f}M', va='center', fontsize=11, color=PALETTE['neutral_dark'])
    ax_a.set_xlabel('Parameters (Millions)', fontsize=14)
    ax_a.set_title('Module-wise Parameter Distribution', fontsize=14, color=PALETTE['neutral_dark'])
    ax_a.spines['bottom'].set_linewidth(2)
    ax_a.spines['left'].set_linewidth(2)
    ax_a.text(-0.06, 1.06, 'a', transform=ax_a.transAxes,
              fontsize=22, fontweight='bold', va='top', ha='right')

    # Panel b: Key architectural innovations table
    ax_b = fig.add_subplot(gs[0, 1])
    ax_b.set_axis_off()
    innovations = [
        ('Pre-LayerNorm', 'Stabilizes gradient flow across transformer layers'),
        ('GELU Activation', 'Smoother gradients vs ReLU; prevents dead neurons'),
        ('5-Channel Gate', 'Adaptive fusion of image & memory via Query/Img/Mem/Divergence/Agreement'),
        ('Multi-Scale DINOv3', 'Extracts features at 25%, 50%, 75%, 100% ViT depths'),
        ('Token Type Embeddings', 'Distinguishes global context tokens from ROI-localized tokens'),
        ('Shared Trunk Heads', 'Classification + Bbox heads share a common semantic representation'),
    ]
    y_pos = 0.9
    ax_b.text(0.0, 1.0, 'Key Architectural Innovations', fontsize=14,
              fontweight='bold', color=PALETTE['neutral_dark'])
    for name, desc in innovations:
        y_pos -= 0.13
        ax_b.text(0.02, y_pos, f'● {name}', fontsize=11, fontweight='bold',
                  color=PALETTE['loss_total'])
        ax_b.text(0.02, y_pos - 0.05, f'    {desc}', fontsize=9, color=PALETTE['neutral'])
    ax_b.text(-0.06, 1.06, 'b', transform=ax_b.transAxes,
              fontsize=22, fontweight='bold', va='top', ha='right')

    out_svg = OUTPUT_DIR / 'fig3_model_summary.svg'
    fig.savefig(out_svg, bbox_inches='tight')
    fig.savefig(OUTPUT_DIR / 'fig3_model_summary.png', dpi=300, bbox_inches='tight')
    plt.close(fig)
    print(f"  ✓ Figure 3: {out_svg}")


# ═══════════════════════════════════════════════════════════════════════
# Shared helpers
# ═══════════════════════════════════════════════════════════════════════

def _draw_stage_shading(ax, stage_boundaries, epoch_boundary_steps):
    """Draw stage background shading on step-based x-axis."""
    stage_colors = [PALETTE['stage1_bg'], PALETTE['stage2_bg'], PALETTE['stage3_bg']]
    sorted_stages = sorted(stage_boundaries.keys())
    for idx, sname in enumerate(sorted_stages):
        if idx >= len(stage_colors):
            break
        sr = stage_boundaries[sname]
        start_ep = sr['start']
        end_ep = sr['end']
        # Find corresponding step indices
        x0 = 0
        x1 = ax.get_xlim()[1]
        if start_ep in epoch_boundary_steps:
            x0 = 0
        if end_ep in epoch_boundary_steps:
            x1 = epoch_boundary_steps[end_ep]
        if end_ep + 1 in epoch_boundary_steps:
            pass
        # Simplified: just use span from first to last
        try:
            # Find first step of start epoch and first step after end epoch
            ep_starts = {k: v for k, v in epoch_boundary_steps.items()}
            x_start = 0
            if start_ep - 1 in ep_starts:
                x_start = ep_starts[start_ep - 1]
            x_end = ax.get_xlim()[1]
            if end_ep in ep_starts:
                x_end = ep_starts[end_ep]
            ax.axvspan(x_start, x_end, alpha=0.25, color=stage_colors[idx], zorder=0)
            mid = (x_start + x_end) / 2
            y_min, y_max = ax.get_ylim()
            ax.text(mid, y_min + 0.02 * (y_max - y_min), sname,
                    ha='center', fontsize=10, color=PALETTE['neutral'],
                    style='italic', alpha=0.7)
        except Exception:
            pass


def _draw_epoch_stage_shading(ax, stage_boundaries):
    """Draw stage background shading on epoch-based x-axis."""
    stage_colors = [PALETTE['stage1_bg'], PALETTE['stage2_bg'], PALETTE['stage3_bg']]
    sorted_stages = sorted(stage_boundaries.keys())
    for idx, sname in enumerate(sorted_stages):
        if idx >= len(stage_colors):
            break
        sr = stage_boundaries[sname]
        ax.axvspan(sr['start'] - 0.5, sr['end'] + 0.5,
                   alpha=0.25, color=stage_colors[idx], zorder=0)
        mid = (sr['start'] + sr['end']) / 2
        y_min, y_max = ax.get_ylim()
        ax.text(mid, y_min + 0.03 * (y_max - y_min), sname,
                ha='center', fontsize=10, color=PALETTE['neutral'],
                style='italic', alpha=0.7)


# ═══════════════════════════════════════════════════════════════════════
# Training report
# ═══════════════════════════════════════════════════════════════════════

def print_report(step_data, epoch_data):
    """Print console training summary."""
    print(f"\n{'='*70}")
    print("  HAMT TRAINING VISUALIZATION REPORT")
    print(f"{'='*70}")

    if step_data:
        losses = [s['loss'] for s in step_data]
        print(f"  Step-level data:  {len(step_data)} steps recorded")
        print(f"  Loss range:       {min(losses):.4f} — {max(losses):.4f}")
        print(f"  Current epoch:    {step_data[-1]['epoch']}")
        print(f"  Current loss:     {step_data[-1]['loss']:.6f}")

    if epoch_data:
        print(f"\n  Epoch-level data: {len(epoch_data)} epochs")
        last = epoch_data[-1]
        print(f"  Final Loss:       {last['loss_total']:.6f}")
        print(f"  Final P@IoU50:    {last['precision_iou50']:.4f}")
        print(f"  Final R@IoU50:    {last['recall_iou50']:.4f}")
        print(f"  Final MatchR:     {last['match_recall']:.4f}")
        print(f"  Final mIoU:       {last['mean_matched_iou']:.4f}")

        # Per-stage summary
        by_stage = defaultdict(list)
        for e in epoch_data:
            by_stage[e.get('stage', 'unknown')].append(e)
        print(f"\n  {'Stage':<10} {'Best P@50':>12} {'Best R@50':>12} {'Best mIoU':>12} {'Min Loss':>12}")
        print(f"  {'-'*60}")
        for sname in sorted(by_stage.keys()):
            sm = by_stage[sname]
            print(f"  {sname:<10} {max(e['precision_iou50'] for e in sm):>12.4f} "
                  f"{max(e['recall_iou50'] for e in sm):>12.4f} "
                  f"{max(e['mean_matched_iou'] for e in sm):>12.4f} "
                  f"{min(e['loss_total'] for e in sm):>12.6f}")


# ═══════════════════════════════════════════════════════════════════════
# Main
# ═══════════════════════════════════════════════════════════════════════

def main():
    log_path, json_path, eval_files = find_data()

    # --- Data loading ---
    step_data = []
    epoch_data = []

    if log_path:
        print(f"Reading training log: {log_path}")
        step_data = extract_step_data(log_path)
        epoch_data = extract_epoch_data(log_path)
        print(f"  Step records: {len(step_data)}")
        print(f"  Epoch summaries: {len(epoch_data)}")

    # Fallback: if no epoch data from log, try JSON
    if not epoch_data and json_path:
        print(f"Fallback: loading JSON metrics from {json_path}")
        epoch_data = load_json_metrics(json_path)
        print(f"  JSON epoch records: {len(epoch_data)}")

    if not step_data and not epoch_data:
        print("No training data found. Please wait for training to produce output.")
        print(f"Expected log path: {OUTPUT_DIR}/train_v4_*.log")
        return

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # --- Build figures ---
    print("\nGenerating Nature-quality visualizations...")
    build_figure1(step_data, epoch_data)
    build_figure2(eval_files)
    build_figure3_model_summary()

    # --- Report ---
    print_report(step_data, epoch_data)

    print(f"\nAll figures saved to: {OUTPUT_DIR}")
    print("  fig1_training_dynamics.svg  — Training loss, decomposition, matching metrics")
    print("  fig2_evaluation.svg         — MOT evaluation metrics (post-eval)")
    print("  fig3_model_summary.svg      — Architecture overview")
    print("\nUse SVG for manuscript editing; PNG for quick preview.")


if __name__ == "__main__":
    main()
